# Generated by Django 4.2.7 on 2023-12-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTest',
        ),
    ]
