# Generated by Django 4.2.7 on 2024-01-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_blog_options_alter_myusers_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
    ]
